package com.example.motionlayout;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    RecyclerView recyclerView;
    RecyclerAdapter recyclerAdapter;
    List<Contentgetset> thumb=new ArrayList<>();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        recyclerView = findViewById(R.id.recyclerview);
        Contentgetset c1 = new Contentgetset(R.drawable.mkbhd, "Brownlee joined YouTube on March 21, 2008. He first started uploading technology videos in January 2009, while still in high school, about new products or reviews of products he already owned.He produced his first videos through screencasting.[12][13] His first several hundred videos were primarily hardware tutorials and freeware. As of December 2019, his channel has gained over 10 million subscribers,[10] making MKBHD one of the most subscribed-to technology-focused YouTube channels, according to Social Blade. Brownlee uploaded his 1000th video on March 29, 2018.\n" +
                "\n" +
                "Brownlee's reviews have been promoted by other review sites as well. Engadget promoted the site in January 2012 when they featured his tour of the then-new cloud storage service called Insync. In November 2013, one of Brownlee's most viral videos was posted based on the LG G Flex, where he performed various scratch tests to portray the self-healing ability of the device. The video reached one million views on the first day. As of December 2019, the video has almost 8 million views. In December 2013, Brownlee did an interview with Motorola CEO Dennis Woodside. In May 2014, Brownlee did the first over-the-air interview with Evan Blass.");

        Contentgetset c2 = new Contentgetset(R.drawable.dhoni, "Mahendra Singh Dhoni (About this soundpronunciation (help·info) born 7 July 1981), is a former Indian international cricketer who captained the Indian national team in limited-overs formats from 2007 to 2016 and in Test cricket from 2008 to 2014. Under his captaincy, India won the inaugural 2007 ICC World Twenty20, the 2010 and 2016 Asia Cups, the 2011 ICC Cricket World Cup and the 2013 ICC Champions Trophy. A right-handed middle-order batsman and wicket-keeper, Dhoni is one of the highest run scorers in One Day Internationals (ODIs) with more than 10,000 runs scored and is considered an effective \"finisher\" in limited-overs formats.[2][3][4] He is widely regarded as one of the best wicket-keeper batsmen and captains in limited-overs format of the game.[5][6][7][8][9] He was also the first wicket-keeper to effect 100 stumpings in ODI cricket.[10]\n" +
                "\n" +
                "Dhoni made his ODI debut on 23 December, 2004 against Bangladesh, and played his first Test a year later against Sri Lanka. He has been the recipient of many awards, including the ICC ODI Player of the Year award in 2008 and 2009 (the first player to win the award twice), the Rajiv Gandhi Khel Ratna award in 2007, the Padma Shri, India's fourth highest civilian honour, in 2009 and the Padma Bhushan, India's third highest civilian honour, in 2018.[11] Dhoni was named as the captain of the ICC World Test XI in 2009, 2010 and 2013. He has also been selected a record 8 times in ICC World ODI XI teams, 5 times as captain. The Indian Territorial Army conferred the honorary rank of Lieutenant Colonel[12] to Dhoni on 1 November 2011. He is the second Indian cricketer after Kapil Dev to receive this honour.");

        Contentgetset c3 = new Contentgetset(R.drawable.abd, "Abraham Benjamin de Villiers (born 17 February 1984), is a South African cricketer. He was named as the ICC ODI Player of the Year three times during his 15-year international career and was one of the five Wisden cricketers of the decade at the end of 2019.\n" +
                "\n" +
                "De Villiers began his international career as a wicket-keeper-batsman, but he has played most often solely as a batsman. He batted at various positions in the batting order, but predominantly in the middle-order. Noted as one of the most innovative and destructive batsmen in the modern era, De Villiers is known for a range of unorthodox shots, particularly behind the wicket-keeper.[3] He made his international debut in a Test match against England in 2004 and first played a One Day International (ODI) in early 2005. His debut in Twenty20 International cricket came in 2006. He scored over 8,000 runs in both Test and ODI cricket and is one of the very few batsmen to have a batting average of over fifty in both forms of the game.[4] In limited overs cricket he is an attacking player.[5] He holds the record for the fastest ODI century in just 31 balls. He also recorded the fastest ODI 50 and 150.\n" +
                "\n" +
                "De Villiers captained South Africa in all three formats, although after a series of injuries he stepped down from the Test captaincy. In 2017 he stepped down from captaining the national limited-overs teams[6] and in May 2018 announced his retirement from all forms of international cricket.[7][8][9] However, in January 2020 De Villiers expressed his intention to make an international comeback and play for South Africa in the 2020 T20 World Cup.[10");
        Contentgetset c4 = new Contentgetset(R.drawable.kamal, "Kamal Haasan (born 7 November 1954) is an Indian actor, dancer, film director, screenwriter, producer, playback singer, lyricist and politician who works primarily in Tamil cinema, Referred to by fans and media as \"Ulaganayagan\". and has also worked in Telugu, Malayalam, Kannada, Hindi and Bengali films. His production company, Raaj Kamal Films International, has produced several of his films. Haasan's contributions to film have been praised by his contemporaries in the across the Indian film industry, and he has been recognised as an influence for actors and filmmakers in the Tamil film industry. He has won four National Film Awards and 19 Filmfare Awards. He was awarded the Kalaimamani award in 1984 the Padma Shri in 1990, the Padma Bhushan in 2014 and the Ordre des Arts et des Lettres (Chevalier) in 2016.[6] He was awarded the Lifetime Achievement Award at 15th Mumbai International Film Festival in 2013.\n" +
                "\n" +
                "Haasan started his career as a child artist in the 1960 Tamil-language film Kalathur Kannamma, for which he won the President's Gold Medal. He met director Vaaranam Vijay who is frequently credited with shaping Haasan's acting skills. His breakthrough as a lead actor came in the 1975 drama Apoorva Raagangal, directed by K. Balachander, in which he played a rebellious youth who falls in love with an older woman. He won his first National Film Award for his portrayal of a guileless school teacher who cares for a woman who suffers from retrograde amnesia in Moondram Pirai (1983). He was noted for his performances in Mani Ratnam's Nayakan (1987) and S. Shankar's vigilante film Indian (1996) and also won second and third National film award respectively. Since then he has appeared in films including Hey Ram (2000), Virumaandi (2004), Dasavathaaram (2008) in which he played ten roles and Vishwaroopam (2013) which were his own productions. Haasan has acted in over 220 films, and in 2019 he became one of the few actors in India to have completed 60 years working in cinema.");
        Contentgetset c5 = new Contentgetset(R.drawable.mkbhd, "Brownlee joined YouTube on March 21, 2008. He first started uploading technology videos in January 2009, while still in high school, about new products or reviews of products he already owned.He produced his first videos through screencasting.[12][13] His first several hundred videos were primarily hardware tutorials and freeware. As of December 2019, his channel has gained over 10 million subscribers,[10] making MKBHD one of the most subscribed-to technology-focused YouTube channels, according to Social Blade. Brownlee uploaded his 1000th video on March 29, 2018.\n" +
                "\n" +
                "Brownlee's reviews have been promoted by other review sites as well. Engadget promoted the site in January 2012 when they featured his tour of the then-new cloud storage service called Insync. In November 2013, one of Brownlee's most viral videos was posted based on the LG G Flex, where he performed various scratch tests to portray the self-healing ability of the device. The video reached one million views on the first day. As of December 2019, the video has almost 8 million views. In December 2013, Brownlee did an interview with Motorola CEO Dennis Woodside. In May 2014, Brownlee did the first over-the-air interview with Evan Blass.");

        Contentgetset c6 = new Contentgetset(R.drawable.dhoni, "Mahendra Singh Dhoni (About this soundpronunciation (help·info) born 7 July 1981), is a former Indian international cricketer who captained the Indian national team in limited-overs formats from 2007 to 2016 and in Test cricket from 2008 to 2014. Under his captaincy, India won the inaugural 2007 ICC World Twenty20, the 2010 and 2016 Asia Cups, the 2011 ICC Cricket World Cup and the 2013 ICC Champions Trophy. A right-handed middle-order batsman and wicket-keeper, Dhoni is one of the highest run scorers in One Day Internationals (ODIs) with more than 10,000 runs scored and is considered an effective \"finisher\" in limited-overs formats.[2][3][4] He is widely regarded as one of the best wicket-keeper batsmen and captains in limited-overs format of the game.[5][6][7][8][9] He was also the first wicket-keeper to effect 100 stumpings in ODI cricket.[10]\n" +
                "\n" +
                "Dhoni made his ODI debut on 23 December, 2004 against Bangladesh, and played his first Test a year later against Sri Lanka. He has been the recipient of many awards, including the ICC ODI Player of the Year award in 2008 and 2009 (the first player to win the award twice), the Rajiv Gandhi Khel Ratna award in 2007, the Padma Shri, India's fourth highest civilian honour, in 2009 and the Padma Bhushan, India's third highest civilian honour, in 2018.[11] Dhoni was named as the captain of the ICC World Test XI in 2009, 2010 and 2013. He has also been selected a record 8 times in ICC World ODI XI teams, 5 times as captain. The Indian Territorial Army conferred the honorary rank of Lieutenant Colonel[12] to Dhoni on 1 November 2011. He is the second Indian cricketer after Kapil Dev to receive this honour.");

        Contentgetset c7 = new Contentgetset(R.drawable.abd, "Abraham Benjamin de Villiers (born 17 February 1984), is a South African cricketer. He was named as the ICC ODI Player of the Year three times during his 15-year international career and was one of the five Wisden cricketers of the decade at the end of 2019.\n" +
                "\n" +
                "De Villiers began his international career as a wicket-keeper-batsman, but he has played most often solely as a batsman. He batted at various positions in the batting order, but predominantly in the middle-order. Noted as one of the most innovative and destructive batsmen in the modern era, De Villiers is known for a range of unorthodox shots, particularly behind the wicket-keeper.[3] He made his international debut in a Test match against England in 2004 and first played a One Day International (ODI) in early 2005. His debut in Twenty20 International cricket came in 2006. He scored over 8,000 runs in both Test and ODI cricket and is one of the very few batsmen to have a batting average of over fifty in both forms of the game.[4] In limited overs cricket he is an attacking player.[5] He holds the record for the fastest ODI century in just 31 balls. He also recorded the fastest ODI 50 and 150.\n" +
                "\n" +
                "De Villiers captained South Africa in all three formats, although after a series of injuries he stepped down from the Test captaincy. In 2017 he stepped down from captaining the national limited-overs teams[6] and in May 2018 announced his retirement from all forms of international cricket.[7][8][9] However, in January 2020 De Villiers expressed his intention to make an international comeback and play for South Africa in the 2020 T20 World Cup.[10");
        Contentgetset c8 = new Contentgetset(R.drawable.kamal, "Kamal Haasan (born 7 November 1954) is an Indian actor, dancer, film director, screenwriter, producer, playback singer, lyricist and politician who works primarily in Tamil cinema, Referred to by fans and media as \"Ulaganayagan\". and has also worked in Telugu, Malayalam, Kannada, Hindi and Bengali films. His production company, Raaj Kamal Films International, has produced several of his films. Haasan's contributions to film have been praised by his contemporaries in the across the Indian film industry, and he has been recognised as an influence for actors and filmmakers in the Tamil film industry. He has won four National Film Awards and 19 Filmfare Awards. He was awarded the Kalaimamani award in 1984 the Padma Shri in 1990, the Padma Bhushan in 2014 and the Ordre des Arts et des Lettres (Chevalier) in 2016.[6] He was awarded the Lifetime Achievement Award at 15th Mumbai International Film Festival in 2013.\n" +
                "\n" +
                "Haasan started his career as a child artist in the 1960 Tamil-language film Kalathur Kannamma, for which he won the President's Gold Medal. He met director Vaaranam Vijay who is frequently credited with shaping Haasan's acting skills. His breakthrough as a lead actor came in the 1975 drama Apoorva Raagangal, directed by K. Balachander, in which he played a rebellious youth who falls in love with an older woman. He won his first National Film Award for his portrayal of a guileless school teacher who cares for a woman who suffers from retrograde amnesia in Moondram Pirai (1983). He was noted for his performances in Mani Ratnam's Nayakan (1987) and S. Shankar's vigilante film Indian (1996) and also won second and third National film award respectively. Since then he has appeared in films including Hey Ram (2000), Virumaandi (2004), Dasavathaaram (2008) in which he played ten roles and Vishwaroopam (2013) which were his own productions. Haasan has acted in over 220 films, and in 2019 he became one of the few actors in India to have completed 60 years working in cinema.");


        thumb.add(c1);
        thumb.add(c2);
        thumb.add(c3);
        thumb.add(c4);
        thumb.add(c5);
        thumb.add(c6);
        thumb.add(c7);
        thumb.add(c8);
        recyclerAdapter = new RecyclerAdapter(thumb, MainActivity.this);
        recyclerView.setAdapter(recyclerAdapter);
        LinearLayoutManager horizontalLayoutManagaer = new LinearLayoutManager(MainActivity.this, LinearLayoutManager.VERTICAL, false);
        recyclerView.setLayoutManager(horizontalLayoutManagaer);
    }
}